esphome:
  name: esphome-web-d05ebc
  friendly_name: ESPHome Web d05ebc
  min_version: "2025.5.0"
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

logger:

api:

uart:
  id: "radar_uart"
  tx_pin: GPIO6
  rx_pin: GPIO7
  baud_rate: 256000

ld2410:
  uart_id: "radar_uart"
  
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
  - platform: gpio
    pin: GPIO5
    name: Radar Output

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO10
    num_leds: 1
    chipset: WS2812B
    name: "LED"

ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ESP32-Fallback"
    password: "fallback_password"

captive_portal:
