

switch:
  - platform: gpio
    id: charger_enable
    name: "${upper_name} Charger Enable"
    pin:
      number: ${charger_enable_pin}
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    id: charging
    pin:
      number: ${charger_status_pin}
      mode: 
        input: true
        pullup: true
      inverted: false
    name: "${upper_name} Charger Status"
    device_class: plug
    filters:
      - delayed_on: 1s
      - delayed_off: 1s
      