# This package supports the LD2410C radar sensor

# The UART is needed to interface with the device.
# Note that the RX/TX pins are named from the perspective of the LD2410C,
# so the TX pin on the radar connects to the RX pin on the ESP32, and vice versa.
uart:
  id: uart_radar
  tx_pin: ${radar_rx_pin} 
  rx_pin: ${radar_tx_pin}
  baud_rate: 256000 
  stop_bits: 1
  parity: NONE

ld2410:
    id: radar_sensor
    uart_id: uart_radar

# Output pin to indicate motion or presence detected
binary_sensor:
  - platform: gpio
    id: radar_out
    pin:
      number: ${radar_out_pin}
      mode: INPUT
      inverted: false
    name: Radar Output
    device_class: motion
    filters:
      - delayed_on: 100ms
      - delayed_off: 1s
    
  - platform: ld2410
    has_target:
        id: bs_presence
        name: Presence

    has_moving_target:
        id: bs_motion
        name: Motion
        on_state:
            then:
                - script.execute: update_led   
                 
    has_still_target:
        id: bs_still
        name: Still Target
        on_state:
            then:
                - script.execute: update_led

    