substitutions:
  intensity: 0.5f  

# This makes a way to control the LED brightness from Home Assistant
globals:
  - id: led_brightness
    type: float
    restore_value: yes
    initial_value: '0.5'   # 50% brightness default

number:
  - platform: template
    id: led_intensity
    name: LED Intensity
    min_value: 0.0
    max_value: 1.0
    step: 0.1
    icon: "mdi:led-on"
    initial_value: '0.5'
    optimistic: true
    set_action:
      - lambda: |-
            id(led_brightness) = x;
            // Update the LED immediately when the intensity changes
            id(update_led).execute();

light:
  - platform: esp32_rmt_led_strip
    id: status_pixel
    pin: ${pixel_pin}
    num_leds: 1
    chipset: ws2812
    rgb_order: GRB
    internal: true

script:
  - id: update_led
    then:
      - lambda: |-
          const float b = id(led_brightness);
          const bool motion   = id(bs_motion).state;
          const bool presence = id(bs_still).state;

          if (motion) {
            // Motion → Red
            auto call = id(status_pixel).turn_on();
            call.set_rgb(1.0f, 0.0f, 0.0f);
            call.set_brightness(b);
            call.perform();
          } else if (presence) {
            // Presence only → Green
            auto call = id(status_pixel).turn_on();
            call.set_rgb(0.0f, 1.0f, 0.0f);
            call.set_brightness(b);
            call.perform();
          } else {
            // Neither → Off
            auto call = id(status_pixel).turn_off();
            call.perform();
          }

